- src/hook.rs
Addresses #1. Fix inspired by https://github.com/linebender/druid/pull/1563
> Use inferred cast in SetWindowLongPtrA call for 32-bit compatibility

- hudhook/src/hooks/dx11.rs
- hudhook/src/hooks/dx12.rs
- hudhook/src/hooks/mod.rs
- hudhook/src/inject.rs
- hudhook/src/lib.rs
Closes #3.
Implements the `hudhook::lifecycle::eject()` function to unhook the previously enabled hooks and invoke `FreeLibraryAndExitThread`.
Also adds a refactor and documentation.
> DLL eject methods for DX11 and DX12

- hudhook/src/hooks/common.rs
- hudhook/src/hooks/dx11.rs
- hudhook/src/hooks/dx12.rs
- hudhook/src/hooks/mod.rs
This is an attempt to reduce a bit code redundancy.
Although this is a bit unnecessary, I've already noticed a few discrepancies between the DX11 and DX12 implementations that actually do the same thing, like DX11 using some functions that DX12 doesn't, and the IO was un-synchronized for DX11 before my PR.
This is more a proposal rather than a fix. With this format, it's more harder to have different WndProc for both implementations so they can be better in sync.
I'm open to discuss this if it's something you'd be up to improve further on or simply drop it.
The `imgui_wnd_proc` is statically dispatched so it should have virtually no performance impact.
> Reduce code redundancy

- Cargo.toml
- src/inject.rs
- tests/inject.rs
Introduces a `Project` struct to control injection. Injection is now performed as follows:
```rust
Process::by_name("notepad.exe").inject(dll_path);
Process::by_title("Untitled - Notepad").inject(dll_path);
```
> Inject overhaul

- src/hooks/dx11.rs
- src/hooks/dx12.rs
- src/hooks/dx9.rs
This patch makes it so that the swapchain we get the vtable from is extracted from the desktop HWND, thus preventing the need to create a window and a class.
> Desktop swapchain

- src/renderers/imgui_dx12.rs
In ImGui there was once a limitation with more than 64k vertexes. To fix this you set this flag
`ctx.io_mut().backend_flags |= BackendFlags::RENDERER_HAS_VTX_OFFSET;`
Which was already done correctly in hudhook, however you need to then use the DrawCmd VtxOffset value when iterating through the draw commands.
For reference:
https://skia.googlesource.com/external/github.com/ocornut/imgui/+/refs/heads/features/draw_callback_extra_arg/examples/imgui_impl_dx12.cpp#231
> Fix for drawing more than 64k draw commands

- src/hooks/dx9.rs
- src/hooks/opengl3.rs
This fixes crashes on resize/reset with DX9 games and likely most of the ejection crashes as discussed here https://github.com/veeenu/hudhook/issues/72
Funny enough - I had seen that Github issue before but didn't realize that was why I had issues with some DX9 games crashing on launch due to them calling the resize/reset function multiple times. Thanks to https://github.com/veeenu/hudhook/issues/73#issuecomment-1412476482 I understood where to look.
I have not yet tried ejecting but I assume that it will still crash sometimes as mentioned in the issue, unless this reset fix makes that go away completely.
> Fix resizing crashes & potentially eject crashes

- src/hooks/common.rs
- tests/dx11.rs
This PR adds a mapping between non-specific modifier keys (e.g. VK_SHIFT) and their concrete respective (eg. VK_RSHIFT and VK_LSHIFT).
> Remap shift/ctrl/menu virtual keys

- src/hooks/dx11.rs
Some computers does not fully support DX11 feature level 11.0, 10.0 does. By adding feature level 10, this will prevent an error in creating `D3D11Device & SwapChain` in those machines.
> DX11 feature level 10 support

- src/hooks/dx9.rs
- src/inject.rs
- tests/inject.rs
This PR fixes an early injection crash that I have (knowingly) only experienced in Fallout 3, but it likely happens in others too.
I honestly am not sure why this works, but changing the d3d9 devicetype from `D3DDEVTYPE_HAL` to `D3DDEVTYPE_NULLREF` makes it stop.
I tested it on 10+ DX9 games without experiencing side-effects, so it should be okay to do this.
Below is the crash I get with `D3DDEVTYPE_HAL`;
> Fix DX9 early inject crash

- src/lib.rs
Reexport `imgui` as a convenience so client libraries can have consistent versioning.
> Reexport imgui

- Cargo.toml
- src/hooks/dx11.rs
- src/lib.rs
We just need to add the feature "log" to tracing and it will automatically use log if no tracing subscriber is active. More info [here](https://docs.rs/tracing/0.1.29/tracing/index.html#log-compatibilityl).
Thoughts? Works flawlessly :)
> Add tracing feature 'log'

- src/hooks/opengl3.rs
This PR will fix ImGui not resetting & thus disappearing in some games when a resize, resolution change or ALT + TAB happens.
We have to compare resolution because some older games (like CS 1.6) don't trigger any window resize when it is in fullscreen and the user changes resolution.
We have to compare window rect because ALT + TAB'ing and changing from windowed to/from fullscreen doesn't always trigger resolution change.
---
The only issue I have noticed so far is that after a bunch of resizes it is possible that everything ImGui renders goes completely black. If you resize again it is possible that it disappears.
I assume there is something more needed for the reset on the OpenGL end - maybe `glClearColor`?
> Fix OpenGL resizing

- src/hooks/common.rs
- src/hooks/dx11.rs
- src/hooks/dx12.rs
- src/hooks/dx9.rs
- src/hooks/mod.rs
- src/hooks/opengl3.rs
This PR adds a contract to the `Hooks` trait. 
This allows third party backends to be implemented by just supplying the constructor around an `ImguiRenderLoop` object.
> Remove `HookableBackend` trait

- Cargo.toml
- src/hooks/dx11.rs
- src/hooks/dx12.rs
- src/hooks/dx9.rs
- src/hooks/opengl3.rs
- src/lib.rs
- src/renderers/imgui_dx12.rs
- src/renderers/imgui_opengl3.rs
Removed the "once_cell" dependency and replaced it with #![feature(once_cell_try)]
Removed the "memoffset" dependency and replaced it with #![feature(offset_of)]
#[stable(feature = "once_cell", since = "1.70.0")]
#[unstable(feature = "offset_of", issue = "106655")]
https://github.com/rust-lang/rust/issues/106655
Did a simple test
1.71.0-nightly
once_cell = "1.8.0"
Debug
std::sync::OnceLock time: 1.8730884s
once_cell::sync::OnceCell time: 4.1763288s
Release
std::sync::OnceLock time: 47.0772ms
once_cell::sync::OnceCell time: 47.0337ms
> Simplify dependencies

- Cargo.toml
- src/hooks/dx12.rs
- src/lib.rs
- src/mh.rs
- src/renderers/imgui_dx12.rs
This PR removes nightly features, temporarily replacing them with crates, thus dropping the `nightly` requirement.
Eventually, we want to remove these dependencies in favor of `std`, but this will suffice for now.
Closes #106.
> Bump dependencies and add feature crates

- src/hooks/common/mod.rs
- src/hooks/common/wnd_proc.rs
- src/hooks/dx11.rs
Closes #86.
The new API currently takes a shared reference to work around concurrency issues, until a proper concurrency overhaul is done.
> Add wnd proc hook to ImguiRenderLoop

- .cargo/config.toml
- Cargo.toml
- src/hooks/mod.rs
- src/lib.rs
Locked all hooks and the injection part behind the feature flags, injection is behind `inject`.
Regarding #96 - It's fixed with this as I only enable OGL3, but there's another new issue that only occur with the Linux -> Windows build process, where it fails get some user profile directory (logged by CE).
Not a big deal, but if you got time to look into it, please do.
> Lock hooks and injection behind feature flags

- examples/dx11_host.rs
- examples/renderers/dx11.rs
- examples/renderers/dx12.rs
- examples/renderers/dx9.rs
- src/hooks/common/mod.rs
- src/hooks/common/wnd_proc.rs
- src/hooks/dx11.rs
- src/hooks/dx12.rs
- src/hooks/mod.rs
- src/lib.rs
- src/renderers/imgui_dx9.rs
- tests/harness/dx11.rs
- tests/harness/dx12.rs
This PR exposes the traits and types in `hooks::common`, and other utilities like the `mh` module, so that third parties can independently implement their own renderers and hooks.
Closes #85.
> Expose `hooks::common`

- README.md
- examples/dx11_hook.rs
- examples/dx12_hook.rs
- examples/dx9_hook.rs
- examples/opengl3_hook.rs
- hudbook/hello-hud/src/lib.rs
- hudbook/src/creating-library/writing-dll.md
- src/hooks/common/mod.rs
- src/hooks/common/wnd_proc.rs
- src/hooks/dx11.rs
- src/hooks/dx12.rs
- src/hooks/dx9.rs
- src/hooks/mod.rs
- src/hooks/opengl3.rs
- src/lib.rs
- tests/dx11.rs
- tests/dx12.rs
- tests/opengl3.rs
This PR deprecates the `ImguiRenderLoopFlags`.
This is a breaking change, but it simplifies the outer API. 
There is no need for that "focused" flag as it was only ever updated by a `WM_ACTIVATE` event. No other events would arrive when the windows is inactive anyway, so there is no way of getting spurious inputs, which the flag was originally intended for anyway, back when the input loop would use `GetAsyncKeyState`.
Closes #120.
> Remove focus flag and `ImguiRenderLoopFlags`

- Cargo.toml
- README.md
- examples/dx11_hook.rs
- examples/dx11_host.rs
- examples/dx12_hook.rs
- examples/dx9_hook.rs
- examples/opengl3_hook.rs
- examples/renderers/dx11.rs
- examples/renderers/dx12.rs
- examples/renderers/dx9.rs
- hudbook/src/creating-library/project-setup.md
- rust-toolchain.toml
- src/hooks/common/mod.rs
- src/hooks/common/wnd_proc.rs
- src/hooks/dx11.rs
- src/hooks/dx12.rs
- src/hooks/dx9.rs
- src/hooks/opengl3.rs
- src/inject.rs
- src/lib.rs
- src/renderers/imgui_dx11.rs
- src/renderers/imgui_dx12.rs
- src/renderers/imgui_dx9.rs
- src/renderers/imgui_opengl3.rs
- src/util.rs
- tests/harness/dx11.rs
- tests/harness/dx12.rs
- tests/harness/dx9.rs
- tests/harness/opengl3.rs
- tests/hook.rs
This PR bumps `windows-rs` to the latest 0.51 version.
There are some new patterns to deal with optional out params that `windows` isn't handling in a very elegant way, e.g. options of options of mutable pointers where the difference between `None` and `Some(null_mut())` is not particularly evident, so some helper functions to deal with these cases should be added and applied:
- `out_param` for pre-allocated out parameters
- `try_out_param` for pre-allocated out parameters in a fallible function
- `out_ptr` for out pointers allocated by the function itself
- `try_out_ptr` for out pointers allocated by a fallible function
Example of usage:
```rust
let desc = try_out_param(|&mut out| device_and_swap_chain.GetDesc(out))?;
```
Blocked by #126
> Bump `windows` to 0.51

- src/hooks/common/mod.rs
Closes #132 
@vars1ty could you please give this branch a spin before I merge it in? If you could please also pipe the logs somewhere and post them that'd be awesome.
I couldn't run the program just yet because I'm setting up a VM. I'd prefer not to run foreign software on my host machine. I can
> Make UnregisterClassW not panic

- Cargo.toml
- src/hooks/dx11.rs
- src/hooks/dx12.rs
- src/hooks/dx9.rs
- src/hooks/opengl3.rs
- src/inject.rs
- src/renderer/pipeline.rs
As per https://github.com/microsoft/windows-rs/issues/1287, instantiating a `windows::core::Error` calls `RoOriginateErrorW` when a message is passed in. This is not available at the moment on Wine.
Since now Wine compatibility is an explicit goal, this PR removes those calls. Running the library at all at the cost of slightly more opaque errors is a reasonable tradeoff.
> Avoid calls to `RoOriginateErrorW`

- Cargo.toml
- build.rs
`hudhook` now compiles with `x86_64-pc-windows-gnu` as well, so the platform requirement in `build.rs` is no longer useful.
> Remove platform block in build.rs

- Cargo.toml
- src/hooks/dx11.rs
- src/hooks/dx12.rs
- src/hooks/dx9.rs
- src/hooks/opengl3.rs
This fixes a bug where `Pipeline::cleanup` is not actually invoked in `eject`, resulting in the window procedure not being reverted.
> Add proper cleanup to Pipeline

- .github/workflows/lint.yml
- Cargo.toml
- src/renderer/input.rs
- src/renderer/keys.rs
- src/renderer/pipeline.rs
The system we have used so far of assigning the key map and then manually updating the `Io::keys_down` field is deprecated in `imgui`.
This PR uses the new system.
> Refactor input to use non-deprecated imgui key i/o system

- src/renderer/input.rs
https://github.com/veeenu/hudhook/issues/172
> Fix the crash caused by the key press

- examples/hook_with_image.rs
- examples/support/mod.rs
- src/lib.rs
- src/renderer/backend/dx11.rs
- src/renderer/backend/dx12.rs
- src/renderer/backend/dx9.rs
- src/renderer/backend/opengl3.rs
- src/renderer/mod.rs
- src/renderer/pipeline.rs
- tests/hook.rs
Fixes #147.
1. add TextureLoader trait with load_texture and replace_texture
2. implement TextureLoader for all 4 engines
* dx9 and dx12: load_texture = heap.create_texture + heap.upload_texture, replace_texture = heap.upload_texture
* dx11 and gl3: load_texture = heap.create_texture (with init), replace_texture = heap.update_texture
"Allow edits by maintainers" is on. If you have any suggestions for improvement, just push changes to this branch, specially about naming and code repetition.
> Replace texture image data

- src/renderer/backend/dx11.rs
When self.ps_instances is none, self.ps_instances_count is 0, then slice::from_raw_parts causes a panic here.
Same for the vs version. Initially I tried this fix with is_some() but it still caused a crash for me.
I don't know if this has any side effects, for me it renders fine after this fix.
> Bugfix panic in D3D11RenderEngine->restore

- Cargo.toml
- src/lib.rs
- src/renderer/mod.rs
- src/renderer/msg_filter.rs
- src/renderer/pipeline.rs
- tests/hook.rs
This PR introduces BREANKING changes described below;
- add MessageFilter to selectively block window message
Blocking every window message blocks intentional user actions like minimizing, closing(Alt-F4 doesn't work either), resizing, etc.
This commit fixes that kind of problem by providing bitflag interface to block certain predefined range of window messages.
To block every messages like before, you can return `MessageFilter::all()` on `set_message_filter()`.
This PR fixes #182.
> add MessageFilter to selectively block window message

- src/renderer/pipeline.rs
According to imgui's custom backend implementation exhibit
and first-party backend implementations,
`io.DeltaTime` is "usually" meant to be updated by backend code.
(you can check platform backend impls of ocornut/imgui for example)
This PR solves issue #186.
> make pipeline reports `delta_time` to imgui

- src/renderer/input.rs
- src/renderer/pipeline.rs
Tried to hook `ImmDisableIME()` out in DS3 and ER to test IME inputs for CJK languages.
Confirmed that it is working fine with these changes (was broken with all `?` characters with IME input).
> Use unicode WinApi functions everywhere to support non-ASCII inputs.

- Cargo.toml
This change exposes imgui's `freetype`, `docking`, and `tables-api` features to developers under the `imgui-freetype`, `imgui-docking`, and `imgui-tables-api` features respectively.
I wanted to use the docking and the new tables api features with hudhook so I figured I should PR this here.
> feat: add imgui features to feature table

- Cargo.toml
- src/hooks/dx12.rs
- src/util.rs
Memory protection flags are set per page so it's enough to check them at page boundaries. (See [here](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualquery#parameters))
This simplifies the code for #209 ([relevant diff](https://github.com/veeenu/hudhook/pull/209/commits/55700fdaf645d0401abe7b9f5571135697afbf76#diff-8841888df06c36a6632525a99403e18778b7de8b8efee5310396fb7b9367ef69R113-R145)) to [this](https://github.com/veeenu/hudhook/pull/210/commits/4cbabb71ad8ac35a943811d1af159839253502d3#diff-8841888df06c36a6632525a99403e18778b7de8b8efee5310396fb7b9367ef69)
I've added a helper function that checks the memory protection at each page boundary in a memory region and returns a slice containing all consecutive readable elements starting from the start of the …
> Check memory protection per page

- .cargo/config.toml
- .gitignore
- Cargo.toml
- src/hooks/dx12.rs
- src/util.rs
This PR changes the selection mechanism for the command queue. Whenever a command queue is detected via the `ExecuteCommandLists` hook, the command queue pointer is matched against the memory next to the swap chain. The assumption is that the swap chain will hold a reference to the command queue it uses. This is predicated on the fact that `CreateSwapChainForHwnd` accepts a command queue in DirectX 12.
A state machine enum implements the requisite logic.
Closes #203.
> Choose command queue associated to swap chain in DirectX 12 hook 

- src/hooks/dx12.rs
- src/hooks/dx9.rs
Hello.
An issue was detected when using this in the latest version of <https://github.com/super-continent/ggxrd-mod>, which is an overlay mod for Guilty Gear Xrd Rev2. It is a Direct3D 9 game. When minimizing and restoring the game's window, there would be a small chance of it crashing with this error:
```
Rendering thread exception:
Result failed 
at A:\Repo\GG-xrd-rev2-netcode\Development\Src\D3D9Drv\Src\D3D9Viewport.cpp:392 
with error D3DERR_INVALIDCALL
```
Reverse engineering efforts pointed to an IDirect3DDevice9::Present() call returning a D3DERR_INVALIDCALL error.
Microsoft's official documentation for Direct3D 9 says:
> Present will fail, returning D3DERR_INVALIDCALL, if called between BeginScene and EndScene pairs
<https://learn.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9- …
> Fix D3DERR_INVALIDCALL returned from Present

- src/util.rs
Not sure how you managed to compile and release without this? The project was not building (The latest release on crates.io was not building for me either however v0.5 was building) this import was missing from the code. 
Edit: Ah I see this might have been added into the prelude in newer versions of Rust. I'm currently pinned on 1.75.0 for some other requirements, this is the only thing seeming to block compiling for that rust version though so couldn't hurt to merge since its just an added import
> fix: missing size_of import
